### ISSUE TITLE
无法播放视频，求大佬帮助

### ISSUE THREAD

**Issue by rgsngdha** [pili-engineering/QPlayer2-Android#14]
-------------------------------------------
新手无法播放视频 403 ，求大佬帮助，是我源码问题，还是 QPlayer2 的原因？
-------------------------------------------
问题：无法播放 https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8 ，其它播放器正常播放。

源码：
                mQSurfacePlayerView = findViewById(R.id.player_view);
        mQSurfacePlayerView.getPlayerControlHandler().init(this);
        mQSurfacePlayerView.getPlayerControlHandler().setDecodeType(QPlayerSetting.QPlayerDecoder.QPLAYER_DECODER_SETTING_AUTO);
        mQSurfacePlayerView.getPlayerControlHandler().setSeekMode(QPlayerSetting.QPlayerSeek.QPLAYER_SEEK_SETTING_NORMAL);
        mQSurfacePlayerView.getPlayerControlHandler().setStartAction(QPlayerSetting.QPlayerStart.QPLAYER_START_SETTING_PLAYING);
        mQSurfacePlayerView.getPlayerControlHandler().setSpeed(1.0F);

        QMediaModelBuilder builder = new QMediaModelBuilder();

        // 无法播放的链接（其它播放器正常播放）
        String url = "https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8";

        // QPlayer2 可以播放的链接
        // String url = "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8";

        builder.addElement("", QURLType.QAUDIO_AND_VIDEO, 0, url, true,"","", QVideoRenderType.PLANE);
        QMediaModel mediaModel = builder.build(false);
        mQSurfacePlayerView.getPlayerControlHandler().playMediaModel(mediaModel, 0);

错误信息：
D/QMedia: 2023-04-23 12:37:05.583 [debug] T-1511261920 /InputStream.cpp L986 avformat_open_input ret=Server returned 403 Forbidden (access denied)
D/QMedia: 2023-04-23 12:37:05.583 [debug] T-1511261920 /InputStream.cpp L968 try open url=https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8 time=1
D/QMedia: 2023-04-23 12:37:06.493 [debug] T-1511261920 /InputStream.cpp L986 avformat_open_input ret=Server returned 403 Forbidden (access denied)
D/QMedia: 2023-04-23 12:37:06.493 [debug] T-1511261920 /InputStream.cpp L968 try open url=https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8 time=2
D/QMedia: 2023-04-23 12:37:07.356 [debug] T-1511261920 /InputStream.cpp L986 avformat_open_input ret=Server returned 403 Forbidden (access denied)
E/QMedia: 2023-04-23 12:37:07.356 [error] T-1511261920 /InputStream.cpp L1003 protocol event context open failed error = Server returned 403 Forbidden (access denied) code=-858797304
E/QMedia: 2023-04-23 12:37:07.356 [error] T-1511261920 /InputStreamComposite.cpp L123 open failed result=0

**Comment by AstaTus** [comment]
你app的网络权限开了吗

**Comment by rgsngdha** [comment]
> 你app的网络权限开了吗

网络权限已经开了。现在使用 [Qplayer2Demo](https://github.com/pili-engineering/QPlayer2-Android/tree/main/Qplayer2Demo)  ，修改播放链接测试，还是无法播放
```

object LongPlayerDataSourceFactory {
    fun create(): CommonPlayerDataSource<LongPlayableParams, LongVideoParams> {
        val dataSourceBuilder =
            CommonPlayerDataSource.DataSourceBuilder<LongPlayableParams, LongVideoParams>()
        var videoParams: LongVideoParams

        var builder = QMediaModelBuilder()
        var url = ""
        var name = ""
        builder = QMediaModelBuilder()

        builder.addElement(
            "", QURLType.QAUDIO_AND_VIDEO, 1080,
             // 修改的链接
            "https://bitdash-a.akamaihd.net/content/sintel/hls/video/250kbit.m3u8", true 
        )
        ...
```

**Comment by AstaTus** [comment]
如果你引入了你自己的工程里的话，是需要开通我们sdk权限的，具体可以联系我们技术支持
