### ISSUE TITLE
需求：音轨切换，调节音调

### ISSUE THREAD

**Issue by tianjianshi1989** [pili-engineering/QPlayer2-Android#6]
这个播放器能否支持多音轨切换，以及音调调节的功能？

**Comment by AstaTus** [comment]
可以支持，在配置 mediamodel时 配置多路 音频清晰度，然后根据 需求切换清晰度
配置多路清晰度示例
https://developer.qiniu.com/pili/12222/qplayer2-core-basic-ability-to-use#1

切换清晰度示例
https://developer.qiniu.com/pili/12222/qplayer2-core-basic-ability-to-use#17

**Comment by AstaTus** [comment]
音调调节 是指？ 变声？

**Comment by AstaTus** [comment]
> 可以支持，在配置 mediamodel时 配置多路 音频清晰度，然后根据 需求切换清晰度 配置多路清晰度示例 https://developer.qiniu.com/pili/12222/qplayer2-core-basic-ability-to-use#1
> 
> 切换清晰度示例 https://developer.qiniu.com/pili/12222/qplayer2-core-basic-ability-to-use#17

用该方式切换
